//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMonitorApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBLogHistory
    {
        public string DBLogId { get; set; }
        public string DBCompanyId { get; set; }
        public string DBCSId { get; set; }
        public string DBIncidentId { get; set; }
        public string DBComponentName { get; set; }
        public string DBIncidentName { get; set; }
        public string DBIncidentDetails { get; set; }
        public Nullable<System.DateTime> DBDateTime { get; set; }
        public string DBStatus { get; set; }
    }
}
