//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMonitorApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBComponent_With_Status
    {
        public DBComponent_With_Status()
        {
            this.DBIncidents = new HashSet<DBIncident>();
        }
    
        public int DBCSId { get; set; }
        public string DBComponentName { get; set; }
        public string DBStatus { get; set; }
        public string DBType { get; set; }
        public Nullable<int> DBCompanyId { get; set; }
        public string DBMasterComponentName { get; set; }
        public string DBCenterName { get; set; }
    
        public virtual DBCompany DBCompany { get; set; }
        public virtual DBMaster_DBComponent_With_Status DBMaster_DBComponent_With_Status { get; set; }
        public virtual ICollection<DBIncident> DBIncidents { get; set; }
    }
}
