//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMonitorApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBLogHistory
    {
        public int DBLogId { get; set; }
        public Nullable<int> DBCompanyId { get; set; }
        public Nullable<int> DBCSId { get; set; }
        public Nullable<int> DBIncidentId { get; set; }
        public string DBComponentName { get; set; }
        public string DBIncidentName { get; set; }
        public string DBIncidentDetails { get; set; }
        public Nullable<System.DateTime> DBDateTimeStart { get; set; }
        public string DBStatus { get; set; }
        public Nullable<System.DateTime> DBDateTimeEnd { get; set; }
    }
}
