//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMonitorApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBMaster_DBComponent_With_Status
    {
        public DBMaster_DBComponent_With_Status()
        {
            this.DBComponent_With_Status = new HashSet<DBComponent_With_Status>();
        }
    
        public string DBMasterComponentName { get; set; }
    
        public virtual ICollection<DBComponent_With_Status> DBComponent_With_Status { get; set; }
    }
}
