//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMonitorApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBSubscription
    {
        public int DBSubscriptionsId { get; set; }
        public string DBName { get; set; }
        public string DBEmail { get; set; }
        public Nullable<int> DBCompanyId { get; set; }
    
        public virtual DBCompany DBCompany { get; set; }
    }
}
