//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMonitorApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBLogin
    {
        public string DBUsername { get; set; }
        public string DBPassword { get; set; }
        public string DBAccountType { get; set; }
    }
}
