//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMonitorApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBCompany
    {
        public DBCompany()
        {
            this.DBCalendars = new HashSet<DBCalendar>();
            this.DBComponent_With_Status = new HashSet<DBComponent_With_Status>();
            this.DBSubscriptions = new HashSet<DBSubscription>();
        }
    
        public string DBCompanyId { get; set; }
        public string DBCompanyName { get; set; }
        public string DBURL { get; set; }
        public string DBPrimaryCenter { get; set; }
        public string DBSecondaryCenter { get; set; }
    
        public virtual ICollection<DBCalendar> DBCalendars { get; set; }
        public virtual ICollection<DBComponent_With_Status> DBComponent_With_Status { get; set; }
        public virtual ICollection<DBSubscription> DBSubscriptions { get; set; }
    }
}
